		api.trains.registerTrainType({
			id: "fr-sbahn",
			name: "Z 58000 (PAR)",
			description: "3-car trainset on the Ho Chi Minh City Metro Line 1. Capable of multiple working for 2 sets for 6 cars.",
			stats: {
				maxSpeed: 30.6,
				maxAcceleration: 1.1,
				maxDeceleration: 1.1,
				maxLateralAcceleration: 1.8,
				maxSlopePercentage: 5.5,
				minTurnRadius: 25,
				parallelTrackSpacing: 4.24,
				trackClearance: 2.10,
				minStationTurnRadius: 600,
				minStationLength: 120,
				maxStationLength: 240,
				maxSpeedLocalStation: 13,
				minCars: 6,
				maxCars: 12,
				carsPerCarSet: 6,
				capacityPerCar: 240,
				carLength: 18.67,
				trainWidth: 3.00,
				carCost: 2500000,
				baseTrackCost: 42500,
				baseStationCost: 77800000,
				scissorsCrossoverCost: 12750000,
				trainOperationalCostPerHour: 400.0,
				carOperationalCostPerHour: 50.0,
				trackMaintenanceCostPerMeter: 300,
				stationMaintenanceCostPerYear: 300,
				stopTimeSeconds: 50,
				tphLimit: 42,
				crossoverSpeed: 6.7, // m/s (~15 mph) — scissors-crossover speed cap
				turnaroundTimeSeconds: (3 * 60 - 50)
			},
			appearance: { color: "#00B4FF" },
			compatibleTrackTypes: ["heavy-metro"],
			maxOverpassSpan: 150
		})
